# Generated by Django 5.1.2 on 2024-10-12 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_name", models.CharField(verbose_name="tag name")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title_post",
                    models.CharField(max_length=100, verbose_name="title post"),
                ),
                (
                    "post_slug",
                    models.SlugField(
                        allow_unicode=True, max_length=100, verbose_name="post slug"
                    ),
                ),
                ("post_body", models.TextField(verbose_name="post body")),
                (
                    "is_publish",
                    models.BooleanField(default=True, verbose_name="is publish"),
                ),
                (
                    "post_like",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="post like"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_staff": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag_name",
                    models.ManyToManyField(related_name="post_tags", to="blogs.tag"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "blog_posts",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment_body", models.TextField(verbose_name="comment body")),
                (
                    "comment_rate",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="comment rate",
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(default=False, verbose_name="is publish"),
                ),
                (
                    "comment_like",
                    models.PositiveIntegerField(default=0, verbose_name="comment like"),
                ),
                (
                    "comment_dislike",
                    models.PositiveIntegerField(
                        default=0, verbose_name="comment dislike"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blogs.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "blog_comments",
            },
        ),
    ]
