# Generated by Django 5.1.2 on 2024-10-12 15:32

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_rename_title_post_post_post_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(max_length=255, verbose_name="category name"),
                ),
                (
                    "category_slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="category slug"
                    ),
                ),
                ("is_publish", models.BooleanField(default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="blogs.postcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
