# Generated by Django 5.1.2 on 2024-10-12 15:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_postcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="blogs.postcategory",
            ),
        ),
    ]
