# Generated by Django 5.1.2 on 2024-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_postcategory_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                related_name="post_category", to="blogs.postcategory"
            ),
        ),
    ]
