# Generated by Django 5.1.2 on 2024-10-13 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_post_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ManyToManyField(
                limit_choices_to={"is_active": True, "is_staff": True},
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
