# Generated by Django 4.2.6 on 2023-10-12 07:51

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersmodel',
            managers=[
                ('objects', accounts.managers.UsersManager()),
            ],
        ),
    ]
