# Generated by Django 4.2.6 on 2023-10-12 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersmodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinformationmodel',
            name='birth_day',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Birthday'),
        ),
    ]
