# Generated by Django 5.1.2 on 2024-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="images/posts/%Y/%m/%d/",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_hash",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="image hash"
            ),
        ),
    ]
